<?php
require_once __DIR__ . '/../../config/db.php';
requireRole('doctor');
$PAGE_TITLE = 'Billing'; $ACTIVE_NAV = 'billing';
$did = $_SESSION['user_id'];
$inv = $conn->query("SELECT i.*, p.full_name AS pname FROM invoices i LEFT JOIN patients p ON i.patient_id=p.patient_id ORDER BY i.created_at DESC LIMIT 50");
include __DIR__ . '/../../includes/layout.php';
?>
<div class="card">
    <div class="card-title">💳 Recent Invoices (read-only)</div>
    <p class="text-muted mb-2">Invoices are generated by reception. You can view status here.</p>
    <table class="data-table">
        <tr><th>Invoice</th><th>Patient</th><th>Description</th><th>Total</th><th>Status</th><th>Method</th></tr>
        <?php while ($i = $inv->fetch_assoc()): ?>
            <tr>
                <td>INV-<?= str_pad($i['invoice_id'],5,'0',STR_PAD_LEFT) ?></td>
                <td><?= e($i['pname']) ?></td>
                <td><?= e($i['description']) ?></td>
                <td>K<?= number_format($i['total'],2) ?></td>
                <td><span class="badge badge-<?= $i['payment_status']==='paid'?'confirmed':'pending' ?>"><?= e($i['payment_status']) ?></span></td>
                <td><?= e($i['payment_method'] ?: '—') ?></td>
            </tr>
        <?php endwhile; ?>
    </table>
</div>
<?php include __DIR__ . '/../../includes/footer.php'; ?>
